# Generated by Django 3.0.8 on 2020-07-20 16:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_conv2d_input'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Input',
        ),
    ]
