# Generated by Django 3.0.8 on 2020-07-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_layers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxPooling2D',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kernel_size', models.CharField(max_length=20)),
                ('strides', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='conv2d',
            name='kernel_size',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='conv2d',
            name='strides',
            field=models.CharField(max_length=20),
        ),
    ]
